# The first cache refresh can take longer than Zabbix agent's default timeout.
Timeout=30

UserParameter=openpbs.node.discovery,/etc/zabbix/scripts/zabbix-openpbs discovery
UserParameter=openpbs.node.problem.count,/etc/zabbix/scripts/zabbix-openpbs count
UserParameter=openpbs.node.problem[*],/etc/zabbix/scripts/zabbix-openpbs problem "$1"
UserParameter=openpbs.node.state[*],/etc/zabbix/scripts/zabbix-openpbs state "$1"
