# The first cache refresh can take longer than Zabbix agent's default timeout.
Timeout=30

UserParameter=openpbs.node.discovery,/usr/local/bin/zabbix-openpbs discovery
UserParameter=openpbs.node.problem.count,/usr/local/bin/zabbix-openpbs count
UserParameter=openpbs.node.problem[*],/usr/local/bin/zabbix-openpbs problem "$1"
UserParameter=openpbs.node.state[*],/usr/local/bin/zabbix-openpbs state "$1"

